"""Route catalog: declarative catalog of data routes with table and column metadata."""
DATA_ROUTES = [
    ("/products", "物料档案", "products", ["id", "code", "name", "specification", "unit", "status"]),
    ("/material", "物料档案", "products", ["id", "code", "name", "specification", "unit", "status"]),
    ("/project-master", "项目档案", "project_masters", ["id", "project_code", "project_name", "customer_id", "status"]),
    ("/machine-serial-master", "机号档案", "machine_serial_masters", ["id", "serial_no", "project_id", "customer_id", "product_id", "status"]),
    ("/customers", "客户档案", "customers", ["id", "name", "contact_person", "phone", "customer_level"]),
    ("/customer", "客户档案", "customers", ["id", "name", "contact_person", "phone", "customer_level"]),
    ("/suppliers", "供应商档案", "suppliers", ["id", "name", "contact_person", "phone"]),
    ("/supplier", "供应商档案", "suppliers", ["id", "name", "contact_person", "phone"]),
    ("/warehouses", "仓库档案", "warehouses", ["id", "code", "name", "status"]),
    ("/warehouse", "仓库档案", "warehouses", ["id", "code", "name", "status"]),
    ("/locations", "库位档案", "locations", ["id", "code", "name", "warehouse_id", "status"]),
    ("/units", "计量单位", "units", ["id", "code", "name", "category", "conversion_rate"]),
    ("/unit", "计量单位", "units", ["id", "code", "name", "category", "conversion_rate"]),
    ("/departments", "部门档案", "departments", ["id", "name", "remark"]),
    ("/department", "部门档案", "departments", ["id", "name", "remark"]),
    ("/employees", "员工档案", "employees", ["id", "name", "department", "phone", "status"]),
    ("/employee", "员工档案", "employees", ["id", "name", "department", "phone", "status"]),
    ("/categories/product", "物料分类", "product_categories", ["id", "name", "code", "remark"]),
    ("/categories/customer", "客户分类", "customer_categories", ["id", "name", "code", "remark"]),
    ("/categories/supplier", "供应商分类", "supplier_categories", ["id", "name", "code", "remark"]),
    ("/categories/warehouse", "仓库分类", "warehouse_categories", ["id", "name", "code", "remark"]),
    ("/business-partners", "业务伙伴", "customers", ["id", "name", "contact_person", "phone"]),
    ("/income-categories", "收入类别列表", "income_categories", ["id", "code", "name", "parent_id", "include_profit", "status"]),
    ("/expense-categories", "支出类别列表", "expense_categories", ["id", "code", "name", "parent_id", "include_profit", "status"]),
    ("/fee-templates", "费用模板列表", "fee_templates", ["id", "template_no", "name", "supplier_name", "department_name", "salesperson_name", "expense_category", "tax_rate", "currency", "payable_amount", "disabled", "status"]),
    ("/auxiliary-data", "辅助资料列表", "auxiliary_data", ["id", "category_name", "code", "name", "status", "remark"]),
    ("/settlement-terms", "结算期限列表", "settlement_terms", ["id", "code", "name", "days", "is_default", "status"]),
    ("/payment-terms", "收付款条件列表", "payment_terms", ["id", "code", "name", "direction", "is_default", "status"]),
    ("/tax-rates", "税率列表", "tax_rates", ["id", "code", "name", "rate", "tax_type", "is_default", "status"]),
    ("/finance/account-mappings", "科目映射列表", "finance_account_mappings", ["id", "mapping_key", "account_code", "account_name", "remark", "updated_at"]),
    ("/currencies", "币别列表", "currencies", ["id", "code", "name", "symbol", "amount_decimals", "price_decimals", "rate_type", "exchange_rate", "rounding_method", "is_base", "status"]),
    ("/settlement-methods", "结算方式", "settlement_methods", ["id", "name", "code", "remark"]),
    ("/cash-bank-accounts", "账户管理列表", "cash_bank_accounts", ["id", "account_code", "account_name", "bank_account_no", "bank_name", "bank_branch", "currency", "account_type", "status"]),
    ("/payment-channels", "支付渠道列表", "payment_channels", ["id", "name", "channel_type", "merchant_no", "settlement_account_code", "settlement_account_name", "wechat_enabled", "alipay_enabled", "status"]),
    ("/master/chart-of-accounts", "会计科目列表", "chart_of_accounts", ["id", "code", "name", "account_type", "balance_direction", "is_leaf", "status"]),
    ("/voucher-words", "凭证字列表", "voucher_words", ["id", "word", "sort_order", "is_default", "status"]),
    ("/voucher-templates", "凭证模板列表", "voucher_templates", ["id", "category", "template_name", "amount_source", "summary", "account_code", "account_name", "auxiliary_accounting", "debit_credit", "amount_ratio", "status"]),
    ("/electronic-accounting-archives", "电子会计档案", "electronic_accounting_archives", ["id", "archive_no", "name", "archive_type", "fiscal_period", "storage_provider", "status"]),
    ("/vat-accounting-data", "增值会计数据列表", "vat_accounting_data", ["id", "scheme_name", "fiscal_period", "audit_status", "generated_status", "generated_by", "generated_at", "status"]),
    ("/transaction-types", "交易类型", "transaction_types", ["id", "name", "code", "remark"]),
    ("/prices/customer", "客户价格", "customer_prices", ["id", "customer_id", "product_id", "price", "status"]),
    ("/prices/supplier", "供应商价格", "supplier_prices", ["id", "supplier_id", "product_id", "price", "status"]),
    ("/prices/tiers", "价格分层", "price_tiers", ["id", "name", "min_qty", "price"]),
    ("/purchases", "采购订单列表", "purchase_orders", ["id", "order_no", "project_code", "serial_no", "status", "total_amount"]),
    ("/purchase-orders", "采购订单列表", "purchase_orders", ["id", "order_no", "project_code", "serial_no", "status", "total_amount"]),
    ("/purchase_receipts", "采购入库列表", "purchase_receipts", ["id", "receipt_no", "status", "project_code", "serial_no"]),
    ("/purchase-requisitions", "采购申请列表", "purchase_requisitions", ["id", "request_no", "status", "remark"]),
    ("/purchase_request", "采购申请列表", "purchase_requisitions", ["id", "request_no", "status", "remark"]),
    ("/purchase-returns", "采购退货列表", "purchase_returns", ["id", "return_no", "status", "total_amount"]),
    ("/supplier-quotes", "供应商报价", "supplier_quotes", ["id", "quote_no", "supplier_id", "status", "total_amount"]),
    ("/payables", "应付账款", "supplier_payables", ["id", "payable_no", "doc_no", "source_no", "amount", "paid_amount", "balance", "status"]),
    ("/sales-orders", "销售订单列表", "sales_orders", ["id", "order_no", "project_code", "serial_no", "status", "total_amount"]),
    ("/shipments", "销售发货列表", "sales_shipments", ["id", "shipment_no", "source_no", "project_code", "serial_no", "status"]),
    ("/quotations", "设备报价列表", "quotation_headers", ["id", "quote_no", "customer_id", "status", "total_amount"]),
    ("/sales-forecasts", "销售预测单列表", "quotation_headers", ["id", "quote_no", "customer_id", "source_no", "project_code", "serial_no", "quote_date", "amount_with_tax", "status"]),
    ("/sales-inquiries", "询价单列表", "quotation_headers", ["id", "quote_no", "customer_id", "source_no", "project_code", "serial_no", "quote_date", "status"]),
    ("/sales-invoices", "销售发票登记列表", "sales_invoices", ["id", "invoice_no", "customer_id", "source_no", "project_code", "serial_no", "invoice_date", "amount_with_tax", "tax_amount", "status"]),
    ("/purchase-invoices", "采购发票登记列表", "purchase_invoices", ["id", "invoice_no", "supplier_id", "source_no", "project_code", "serial_no", "invoice_date", "amount_with_tax", "tax_amount", "status"]),
    ("/sales-returns", "销售退货列表", "sales_returns", ["id", "return_no", "status", "total_amount"]),
    ("/sales-return-requests", "销售退货申请列表", "sales_returns", ["id", "return_no", "source_no", "project_code", "serial_no", "customer_id", "return_date", "amount_with_tax", "status"]),
    ("/sales-exchange-requests", "销售换货申请列表", "sales_returns", ["id", "return_no", "source_no", "project_code", "serial_no", "customer_id", "return_date", "amount_with_tax", "status"]),
    ("/sales-tax-registrations", "销售税票登记列表", "sales_invoices", ["id", "invoice_no", "customer_id", "source_no", "project_code", "serial_no", "invoice_date", "amount_with_tax", "tax_amount", "status"]),
    ("/sales-reconciliations", "销售对等核销列表", "customer_receivables", ["id", "source_no", "project_code", "serial_no", "customer_id", "total_amount", "received_amount", "balance", "status"]),
    ("/receivables", "应收账款", "customer_receivables", ["id", "receivable_no", "source_no", "project_code", "serial_no", "total_amount", "received_amount", "balance", "status"]),
    ("/inventory/detail", "库存明细", "inventory_balances", ["id", "product_id", "warehouse_id", "location_id", "quantity"]),
    ("/inventory/summary", "库存汇总", "inventory_balances", ["id", "product_id", "quantity"]),
    ("/inventory/aging", "库存账龄", "inventory_balances", ["id", "product_id", "quantity", "created_at"]),
    ("/inventory/expiry", "库存效期", "batch_tracking", ["id", "product_id", "lot_no", "expiry_date", "quantity"]),
    ("/transactions", "库存流水", "stock_transactions", ["id", "product_id", "transaction_type", "quantity", "reference_no"]),
    ("/inventory_alerts", "库存预警", "inventory_alerts", ["id", "product_id", "alert_type", "status"]),
    ("/batch/tracking", "批次机号追溯", "batch_tracking", ["id", "product_id", "project_code", "lot_no", "serial_no", "quantity_available"]),
    ("/inventory_checks", "库存盘点列表", "inventory_check_orders", ["id", "check_no", "status", "remark"]),
    ("/transfers", "库存调拨列表", "transfer_orders", ["id", "transfer_no", "status", "remark"]),
    ("/adjustments", "库存调整列表", "inventory_adjustments", ["id", "adj_no", "status", "remark"]),
    ("/inventory/inbound", "其他入库单列表", "stock_transactions", ["id", "reference_no", "transaction_type", "tx_date", "project_code", "serial_no"]),
    ("/inventory/outbound", "其他出库单列表", "stock_transactions", ["id", "reference_no", "transaction_type", "tx_date", "project_code", "serial_no"]),
    ("/equipment", "设备台账", "equipment", ["id", "code", "name", "model", "status"]),
    ("/assembly-orders", "组装单列表", "inventory_assembly_orders", ["id", "assembly_no", "doc_date", "project_code", "serial_no", "status"]),
    ("/disassembly-orders", "拆卸单列表", "inventory_assembly_orders", ["id", "assembly_no", "doc_date", "project_code", "serial_no", "status"]),
    ("/work-orders", "生产工单列表", "work_orders", ["id", "wo_no", "project_code", "serial_no", "status", "quantity"]),
    ("/production-issues", "生产领料单列表", "pick_lists", ["id", "doc_no", "work_order_id", "project_code", "serial_no", "status"]),
    ("/production-returns", "生产退料单列表", "pick_lists", ["id", "doc_no", "work_order_id", "project_code", "serial_no", "status"]),
    ("/production-completions", "完工入库单列表", "production_completion_orders", ["id", "completion_no", "work_order_id", "project_code", "serial_no", "status"]),
    ("/production/operation-reports", "工序报工单列表", "operation_reports", ["id", "report_no", "work_order_id", "report_type", "status"]),
    ("/work-centers", "工作中心", "work_centers", ["id", "code", "name", "status"]),
    ("/production-routings", "工艺路线", "production_routings", ["id", "routing_no", "product_id", "status"]),
    ("/production-schedules", "生产排程", "production_schedules", ["id", "schedule_no", "status", "planned_start_date"]),
    ("/production-enhance/mrp-requirements", "MRP缺料", "mrp_requirements", ["id", "product_id", "project_code", "serial_no", "shortage_quantity", "status"]),
    ("/production-enhance/quality-inspections", "质量检验列表", "quality_inspection_records", ["id", "inspection_no", "status", "created_at"]),
    ("/subcontract", "委外订单列表", "subcontract_orders", ["id", "order_no", "project_code", "serial_no", "status"]),
    ("/subcontract-orders", "委外订单列表", "subcontract_orders", ["id", "order_no", "project_code", "serial_no", "status"]),
    ("/subcontract_issue", "委外发料单列表", "subcontract_issue_orders", ["id", "issue_no", "date", "subcontract_order_id", "supplier_id", "status"]),
    ("/subcontract_receive", "委外收货单列表", "subcontract_receive_orders", ["id", "receive_no", "date", "subcontract_order_id", "supplier_id", "status"]),
    ("/requisition", "工单领料处理", "pick_lists", ["id", "pick_no", "status", "remark"]),
    ("/bom", "BOM清单", "bom_headers", ["id", "bom_no", "product_id", "status"]),
    ("/engineering/kitting", "齐套检查", "mrp_requirements", ["id", "product_id", "project_code", "serial_no", "shortage_quantity", "status"]),
    ("/service-cards", "设备服务档案", "machine_service_cards", ["id", "card_no", "serial_no", "project_code", "machine_model", "status"]),
    ("/service-orders", "售后服务单列表", "machine_service_orders", ["id", "order_no", "project_code", "serial_no", "service_date", "service_type", "status"]),
    ("/service-acceptance", "安装验收列表", "machine_service_acceptance_checks", ["id", "acceptance_no", "check_date", "checklist_type", "item_name", "result"]),
    ("/service-return-visits", "售后回访列表", "machine_service_return_visits", ["id", "visit_no", "visit_date", "satisfaction", "satisfaction_score", "result", "next_action"]),
    ("/service-rmas", "RMA列表", "machine_service_rmas", ["id", "rma_no", "project_code", "serial_no", "rma_date", "status", "claim_status"]),
    ("/mrp/runs", "MRP运算列表", "mrp_runs", ["id", "run_no", "source_type", "source_id", "project_id", "serial_no", "bom_version_id", "status", "created_by", "created_at"]),
    ("/mrp/suggestions", "MRP建议列表", "mrp_suggestions", ["id", "run_id", "suggestion_type", "material_id", "qty", "required_date", "status", "converted_doc_type", "converted_doc_id"]),
    ("/cost/runs", "成本计算列表", "cost_runs", ["id", "run_no", "period", "project_id", "serial_no", "status", "created_by", "created_at"]),
    ("/bom/versions", "BOM版本列表", "bom_versions", ["id", "bom_id", "version_no", "status", "effective_date", "expire_date", "approved_by", "approved_at"]),
    ("/ecn/impact-tasks", "ECN影响任务列表", "ecn_impact_results", ["id", "ecn_id", "affected_type", "affected_id", "impact_level", "action_required", "status"]),
    ("/ecn/action-tasks", "ECN执行任务列表", "ecn_action_tasks", ["id", "ecn_id", "task_type", "description", "assignee_id", "status", "created_at"]),
    ("/trace/integrity", "追溯完整性检查", "trace_integrity_findings", ["id", "check_type", "doc_type", "doc_id", "severity", "status", "created_at"]),
    ("/trace/snapshots", "追溯快照列表", "trace_snapshots", ["id", "doc_type", "doc_id", "doc_no", "snapshot_event", "project_code", "serial_no", "created_at"]),
    ("/security/data-permissions", "数据权限规则", "data_permission_rules", ["id", "subject_type", "subject_id", "scope_type", "scope_id", "permission", "created_at"]),
    ("/security/data-access-logs", "数据访问日志", "data_access_logs", ["id", "user_id", "resource_type", "resource_id", "action", "allowed", "reason", "created_at"]),
    ("/security/export-approvals", "导出审批", "export_approval_requests", ["id", "requester_id", "resource_type", "resource_label", "export_format", "status", "created_at"]),
    ("/finance/vouchers", "凭证列表", "vouchers", ["id", "voucher_no", "amount", "status"]),
    ("/users", "用户", "users", ["id", "username", "full_name", "role", "created_at"]),
    ("/permissions/manage", "权限管理", "permissions", ["id", "code", "name", "remark"]),
    ("/permissions/roles", "角色权限", "role_permissions", ["id", "role_id", "permission_id"]),
    ("/approval/pending", "待审批", "approval_records", ["id", "status", "created_at"]),
    ("/approval/records", "审批记录", "approval_records", ["id", "status", "created_at"]),
    ("/operation_logs", "操作日志", "operation_logs", ["id", "username", "action", "target", "created_at"]),
    ("/system/options", "系统参数", "system_options", ["id", "option_key", "option_value", "remark"]),
    ("/system/doc-rules", "单据编号设置", "erp_code_rules", ["rule_key", "prefix", "date_format", "sequence_length", "reset_scope", "is_active"]),
    ("/system/opening-period", "开账时间/启用期间", "system_options", ["option_key", "option_value", "remark", "updated_at"]),
]

WORKBENCH_ROUTES = [
    ("/project-delivery-workbench", "项目交付工作台", "workbench", ["project_code", "serial_no", "blocked_reason", "next_step"]),
    ("/mrp", "MRP工作台", "workbench", ["run_no", "source_type", "project_id", "serial_no", "status"]),
    ("/trace", "追溯工作台", "workbench", ["project_code", "serial_no", "doc_type", "doc_id"]),
    ("/cost", "成本工作台", "workbench", ["run_no", "period", "project_id", "serial_no", "status"]),
]

HELP_ROUTES = [
    ("/help/assistant", "ERP operation assistant", "system_help", ["manual_section", "question"]),
    ("/help/operation-manual", "ERP operation manual", "system_help", ["section", "workflow", "entry"]),
    ("/api/ai-assistant/help", "ERP operation assistant guidance API", "system_help", ["question", "manual_section"]),
]

REPORT_ROUTES = [
    ("/sales/reports/summary", "销售汇总表", "sales_orders"),
    ("/sales/reports/order-execution-summary", "销售订单执行汇总", "sales_orders"),
    ("/sales/reports/order-execution-detail", "销售订单执行明细", "sales_orders"),
    ("/sales/reports/customer-open-order-analysis", "客户未交订单分析", "sales_orders"),
    ("/sales/reports/project-serial-open-order-analysis", "项目/机号未交订单分析", "sales_orders"),
    ("/sales/reports/receivable-aging", "销售应收账龄分析", "customer_receivables"),
    ("/sales/reports/project-serial-order-tracking", "项目/机号销售订单跟踪", "sales_orders"),
    ("/sales/reports/shipment-execution-detail", "销售发货执行明细", "sales_shipments"),
    ("/sales/reports/shipped-goods-detail", "发出商品明细", "sales_shipments"),
    ("/sales/reports/shipped-goods-summary", "发出商品汇总", "sales_shipments"),
    ("/sales/reports/shipped-unsettled-detail", "销售发货未结明细", "sales_shipments"),
    ("/sales/reports/invoice-execution-detail", "销售开票执行明细", "sales_invoices"),
    ("/sales/reports/invoice-summary", "销售发票汇总表", "sales_invoices"),
    ("/sales/reports/receivable-collection-detail", "销售收款执行明细", "customer_receipts"),
    ("/sales/reports/project-serial-gross-margin", "项目/机号销售毛利分析", "sales_shipments"),
    ("/sales/reports/price-execution-analysis", "销售价格执行分析", "sales_order_items"),
    ("/sales/reports/delivery-delay-analysis", "销售交付逾期分析", "sales_orders"),
    ("/sales/reports/operation-snapshot", "销售经营快照", "sales_orders"),
    ("/sales/reports/daily", "销售日报", "sales_orders"),
    ("/reports_enhanced", "增强报表", "financial_reports"),
    ("/engineering/project-plan", "工程项目计划", "engineering_project_milestones"),
    ("/system", "系统查询", "system_options"),
    ("/system/readiness", "系统就绪检查", "system_options"),
    ("/system/data-health", "数据健康", "system_options"),
    ("/system/data-health/master/<check_key>", "主数据健康明细", "system_options"),
    ("/system/doc-rules", "单号规则", "doc_numbering_rules"),
    ("/system/trial-run-report", "试运行报告", "system_options"),
    ("/system/restore-guide", "恢复指南", "system_options"),
    ("/barcode/lookup", "条码查询", "product_barcodes"),
    ("/mrp/kitting", "齐套分析", "mrp_run_items"),
    ("/mrp/runs/<id>", "MRP运算明细", "mrp_run_items"),
    ("/trace/project/<project_code>", "项目追溯", "trace_links"),
    ("/trace/serial/<serial_no>", "机号追溯", "trace_links"),
    ("/trace/document/<doc_type>/<doc_id>", "单据追溯", "trace_links"),
    ("/cost/runs/<id>", "成本计算明细", "cost_run_items"),
    ("/cost/project/<project_code>", "项目成本汇总", "cost_run_items"),
    ("/cost/serial/<serial_no>", "机号成本汇总", "cost_run_items"),
    ("/cost/reconciliation", "成本对账", "cost_reconciliation_results"),
    ("/bom/<bom_id>/versions", "BOM版本列表", "bom_versions"),
    ("/bom/versions/<id>", "BOM版本明细", "bom_versions"),
    ("/work-orders/<id>/snapshots", "工单快照", "work_order_bom_snapshots"),
    ("/ecn/<id>/impact", "ECN影响分析", "ecn_impact_results"),
    ("/bom/items/<id>/substitutes", "BOM替代料", "bom_substitute_materials"),
]

REPORT_PAGE_REDIRECTS = {
    "/reports_enhanced": "/finance/reports",
    "/report-analysis/dashboard": "/sales/reports",
    "/report-analysis/business-analysis": "/sales/reports",
    "/report-analysis/sales-ranking": "/sales/reports",
    "/report-analysis/profit-analysis": "/finance/reports",
    "/report-analysis/project-profit": "/finance/reports",
    "/report-analysis/subscription-reports": "/system-enhance/custom-reports",
    "/finance/financial-reports": "/finance/reports",
    "/inventory/monthly-report": "/inventory/reports",
    "/production-enhance/quality-reports": "/production/reports",
    "/production-enhance/labor-analysis": "/production/reports",
    "/production-enhance/work-order-cost-analysis": "/production/reports",
}

FINANCE_PHASE1_ROUTE_CLASSIFICATION = {
    "/finance/accounts": {
        "classification": "internal",
        "page_type": "finance_master_boundary",
        "owner": "finance",
        "boundary": "chart of accounts is maintained through /master/chart-of-accounts; this legacy finance path is internal and not exposed in normal navigation",
    },
    "/finance/assets": {
        "classification": "hidden",
        "page_type": "finance_module_boundary",
        "owner": "finance",
        "boundary": "fixed assets are out of finance phase 1; hidden until asset lifecycle scope is approved",
    },
    "/finance/vouchers": {
        "classification": "readonly",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "voucher drafts/list only; read-only review, no posting, reverse posting, tax, statutory general ledger, payroll, or fixed asset handling",
    },
    "/finance/vouchers/generate": {
        "classification": "readonly",
        "page_type": "report",
        "owner": "finance",
        "boundary": "read-only voucher generation preview; shows pending source documents and generated voucher status",
    },
    "/finance/vouchers/generate-batch": {
        "classification": "live",
        "page_type": "finance_document_entry",
        "owner": "finance",
        "boundary": "C-1 controlled voucher generation: select sales/purchase invoices, receipts, payments to generate draft vouchers; operator reviews and posts separately",
    },
    "/finance/bank-statements": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "C-2 bank statement list and import management; imports CSV bank statements and matches against cash_bank_journal_entries",
    },
    "/finance/bank-statements/import": {
        "classification": "live",
        "page_type": "finance_document_entry",
        "owner": "finance",
        "boundary": "C-2 bank statement CSV import form; creates bank_statements and bank_statement_lines records",
    },
    "/finance/bank-statements/<int:statement_id>": {
        "classification": "live",
        "page_type": "finance_document_detail",
        "owner": "finance",
        "boundary": "C-2 bank statement detail with match status; supports auto-match and manual match actions",
    },
    "/finance/bank-statements/<int:statement_id>/auto-match": {
        "classification": "live",
        "page_type": "finance_document_action",
        "owner": "finance",
        "boundary": "C-2 auto-match bank statement lines against cash_bank_journal_entries by amount/date/counterparty",
    },
    "/finance/bank-statements/lines/<int:line_id>/match": {
        "classification": "live",
        "page_type": "finance_document_action",
        "owner": "finance",
        "boundary": "C-2 manual match a bank statement line to a specific journal entry",
    },
    "/finance/bank-statements/lines/<int:line_id>/unmatch": {
        "classification": "live",
        "page_type": "finance_document_action",
        "owner": "finance",
        "boundary": "C-2 unmatch a previously matched bank statement line",
    },
    "/finance/bank-statements/lines/<int:line_id>/unmatched-journals": {
        "classification": "internal",
        "page_type": "api",
        "owner": "finance",
        "boundary": "C-2 JSON API returning unmatched journal entries for manual match modal",
    },
    "/finance/fx-rates": {
        "classification": "live",
        "page_type": "finance_master_data",
        "owner": "finance",
        "boundary": "C-5 exchange rate history maintenance; supports create/update period-end rates",
    },
    "/finance/fx-adjustments": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "C-5 FX period-end adjustment run list; scans open AR/AP balances and computes unrealized gain/loss",
    },
    "/finance/fx-adjustments/run": {
        "classification": "live",
        "page_type": "finance_document_action",
        "owner": "finance",
        "boundary": "C-5 execute FX period-end adjustment for a given period",
    },
    "/finance/fx-adjustments/<int:run_id>": {
        "classification": "readonly",
        "page_type": "finance_document_detail",
        "owner": "finance",
        "boundary": "C-5 FX adjustment run detail with per-line gain/loss breakdown",
    },
    "/finance/financial-statements": {
        "classification": "readonly",
        "page_type": "report",
        "owner": "finance",
        "boundary": "operating finance snapshot only; not statutory financial statements or general ledger reports",
    },
    "/finance/period-close": {
        "classification": "live",
        "page_type": "document_action",
        "owner": "finance",
        "boundary": "generate, audit and lock operating finance snapshot; self-service reverse close is not exposed",
    },
    "/finance/exchange-adjustment": {
        "classification": "live",
        "page_type": "finance_action",
        "owner": "finance",
        "boundary": "period-end foreign currency exchange adjustment for cash/bank accounts; generate and audit exchange adjustment documents only",
    },
    "/finance/exchange-adjustments": {
        "classification": "readonly",
        "page_type": "document_list",
        "owner": "finance",
        "boundary": "exchange adjustment document query and export only; new adjustment work is handled by the independent action route",
    },
    "/finance/sales-invoices": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "standard finance sales invoice registration entry; delegates to existing sales invoice list, no tax-control, declaration, or automatic voucher posting",
    },
    "/finance/purchase-invoices": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "standard finance purchase invoice registration entry; delegates to existing purchase invoice list, no tax-control, declaration, or automatic voucher posting",
    },
    "/finance/receivables/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance receivable detail alias; redirects to the existing receivable detail without changing posting or settlement logic",
    },
    "/finance/receipts/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance receipt detail alias; redirects to the existing customer receipt detail workflow",
    },
    "/finance/advance-receipts/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance advance receipt detail alias; redirects to the existing customer advance receipt detail workflow",
    },
    "/finance/receipt-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance receipt refund detail alias; redirects to the existing customer receipt refund detail workflow",
    },
    "/finance/advance-receipt-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance advance receipt refund detail alias; redirects to the existing customer advance refund detail workflow",
    },
    "/finance/other-income/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance other income detail alias; redirects to the existing customer other income detail workflow",
    },
    "/finance/other-income-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance other income refund detail alias; redirects to the existing customer other income refund detail workflow",
    },
    "/finance/payables/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance payable detail alias; redirects to the existing payable detail without changing posting or settlement logic",
    },
    "/finance/payments/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance payment detail alias; redirects to the existing supplier payment detail workflow",
    },
    "/finance/advance-payments/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance advance payment detail alias; redirects to the existing supplier advance payment detail workflow",
    },
    "/finance/payment-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance payment refund detail alias; redirects to the existing supplier payment refund detail workflow",
    },
    "/finance/advance-payment-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance advance payment refund detail alias; redirects to the existing supplier advance refund detail workflow",
    },
    "/finance/other-expenses/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance other expense detail alias; redirects to the existing supplier other expense detail workflow",
    },
    "/finance/other-expense-refunds/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance other expense refund detail alias; redirects to the existing supplier other expense refund detail workflow",
    },
    "/finance/sales-invoices/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance sales invoice detail alias; redirects to the existing sales invoice detail without tax-control or voucher posting changes",
    },
    "/finance/purchase-invoices/<id>": {
        "classification": "live",
        "page_type": "finance_document_detail_alias",
        "owner": "finance",
        "boundary": "canonical finance purchase invoice detail alias; redirects to the existing purchase invoice detail without tax-control or voucher posting changes",
    },
    "/sales-invoices": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "invoice registration list only; no tax-control, declaration, or automatic voucher posting",
    },
    "/purchase-invoices": {
        "classification": "live",
        "page_type": "finance_document_list",
        "owner": "finance",
        "boundary": "invoice registration list only; no tax-control, declaration, or automatic voucher posting",
    },
}

# P0 first-phase core engine route boundary classification.
# Each entry mirrors the MENU_ROLLOUT_CLASSIFICATION.md P0 sections and records
# the page type, owner, and business boundary for audit scripts.
P0_ROUTE_CLASSIFICATION = {
    # P0-1 MRP / kitting net-requirement engine
    "/mrp": {
        "classification": "live",
        "page_type": "workbench",
        "owner": "production/planning",
        "boundary": "MRP home/workbench; entry to run MRP, view run history, suggestions, and kitting analysis only",
    },
    "/mrp/run": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/planning",
        "boundary": "execute MRP run from sales order, project, serial, work order, or manual product/BOM; persists run snapshot, items, and suggestions",
    },
    "/mrp/runs": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "production/planning",
        "boundary": "MRP run history list; search, status, next action, and detail links only",
    },
    "/mrp/runs/<id>": {
        "classification": "live",
        "page_type": "document_detail",
        "owner": "production/planning",
        "boundary": "MRP run detail; shows source, BOM version, snapshot, net-requirement items, and suggestions",
    },
    "/mrp/suggestions": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "production/planning",
        "boundary": "MRP suggestions list; supports single and batch convert to purchase requisition, work order, or subcontract order",
    },
    "/mrp/suggestions/<id>/convert": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/planning",
        "boundary": "convert a single MRP suggestion into a target document; writes trace_link to the new document",
    },
    "/mrp/suggestions/batch-convert": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/planning",
        "boundary": "batch convert selected MRP suggestions into target documents",
    },
    "/mrp/kitting": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "production/planning",
        "boundary": "kitting analysis query; shows coverage, shortage, and kitting rate by project/serial/work order; no document write actions",
    },
    "/api/mrp/runs/<id>/suggestions": {
        "classification": "readonly",
        "page_type": "internal_api",
        "owner": "production/planning",
        "boundary": "JSON endpoint returning suggestions for a given MRP run; consumed by the run detail page",
    },
    # P0-2 project/serial full-chain trace engine
    "/trace": {
        "classification": "live",
        "page_type": "workbench",
        "owner": "production/project",
        "boundary": "trace home/workbench; entry to project, serial, and document trace pages",
    },
    "/trace/project/<project_code>": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "project",
        "boundary": "forward and reverse trace by project code; read-only graph and timeline",
    },
    "/trace/serial/<serial_no>": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "production/service",
        "boundary": "forward and reverse trace by machine serial number; read-only graph and timeline",
    },
    "/trace/document/<doc_type>/<doc_id>": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "all",
        "boundary": "trace from any business document to its upstream and downstream documents; read-only",
    },
    "/trace/integrity": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "system",
        "boundary": "trace integrity findings list; shows missing links, missing project/serial fields, and completeness score",
    },
    "/trace/integrity/<id>/resolve": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "resolve a trace integrity finding after the underlying data is corrected",
    },
    "/trace/integrity/scan": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "trigger a trace integrity re-scan; writes new findings to trace_integrity_findings",
    },
    "/trace/integrity/backfill": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "P4-B2: backfill missing trace_links rows and missing project_code/serial_no fields on downstream documents, then mark corresponding open findings as resolved",
    },
    # P0-3 single-machine / project cost collection engine
    "/cost": {
        "classification": "live",
        "page_type": "workbench",
        "owner": "finance/production",
        "boundary": "cost engine home/workbench; entry to run cost calculation, view runs, project/serial summaries, and reconciliation",
    },
    "/cost/run": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "finance",
        "boundary": "execute a cost calculation run for a period, project, and/or serial; collects material, labor, overhead, outsource, service, and quality costs",
    },
    "/cost/runs": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "finance",
        "boundary": "cost run history list; search, status, next action, and detail links only",
    },
    "/cost/runs/<id>": {
        "classification": "live",
        "page_type": "document_detail",
        "owner": "finance",
        "boundary": "cost run detail; shows cost items by type, source document, project, serial, and work order",
    },
    "/cost/project/<project_code>": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "finance/project",
        "boundary": "project cost summary; read-only cost composition and source drill-down",
    },
    "/cost/serial/<serial_no>": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "finance/production",
        "boundary": "serial cost summary; read-only single-machine cost composition and source drill-down",
    },
    "/cost/reconciliation": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "finance",
        "boundary": "cost reconciliation results; compares business cost vs inventory cost vs GL cost",
    },
    "/cost/reconciliation/run": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "finance",
        "boundary": "execute a cost reconciliation run for a period; saves results to cost_reconciliation_results",
    },
    "/cost/variance": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "finance",
        "boundary": "standard vs actual cost variance report; read-only summary by cost type and detail lines",
    },
    # P0-4 BOM / drawing / process / ECN snapshot and impact control
    "/bom/versions": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "engineering",
        "boundary": "BOM version list across all BOMs; search, status, next action, and detail links only",
    },
    "/bom/<bom_id>/versions": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "engineering",
        "boundary": "BOM version list scoped to a single BOM; separate from the BOM entry page",
    },
    "/bom/versions/<id>": {
        "classification": "live",
        "page_type": "document_detail",
        "owner": "engineering",
        "boundary": "BOM version detail; shows status, effective/expire dates, approver, and linked work-order snapshots",
    },
    "/bom/versions/new": {
        "classification": "live",
        "page_type": "document_entry",
        "owner": "engineering",
        "boundary": "BOM version creation form/action; creates a draft version tied to an existing BOM",
    },
    "/bom/versions/<id>/approve": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "approve a draft BOM version; transitions draft to approved",
    },
    "/bom/versions/<id>/release": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "release an approved BOM version; atomically expires prior released versions of the same BOM",
    },
    "/bom/versions/<id>/obsolete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "mark a released BOM version obsolete",
    },
    "/work-orders/<id>/snapshots": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "engineering/production",
        "boundary": "work-order BOM/process/drawing snapshots; read-only view of the versions frozen at work-order release",
    },
    "/ecn/<id>/impact": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "engineering",
        "boundary": "ECN impact analysis result view; read-only list of affected sales orders, purchase orders, work orders, subcontract orders, and inventory",
    },
    "/ecn/<id>/impact/analyze": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "run ECN impact analysis; writes results to ecn_impact_results",
    },
    "/ecn/impact-tasks/<id>/resolve": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "resolve an ECN impact task after the affected document is handled",
    },
    "/ecn/impact-tasks": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "engineering",
        "boundary": "ECN impact tasks list; search, status, next action, and detail links only",
    },
    "/bom/items/<id>/substitutes": {
        "classification": "readonly",
        "page_type": "query_list",
        "owner": "engineering",
        "boundary": "BOM item substitutes list; read-only view of substitute materials and approval status",
    },
    "/bom/items/<id>/substitutes/new": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "create a substitute material for a BOM item; upsert on bom_item_id, substitute_product_id",
    },
    "/bom/substitutes/<id>/edit": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "edit an existing substitute material's priority, ratio, and auto-substitute flag",
    },
    "/bom/substitutes/<id>/approve": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "approve a pending substitute material",
    },
    "/bom/substitutes/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "delete a substitute material; restricted to unapproved or superseded rows",
    },
    "/ecn/action-tasks": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "engineering",
        "boundary": "ECN action tasks list across all ECNs; search, status, owner, and next action only",
    },
    "/ecn/<id>/action-tasks": {
        "classification": "live",
        "page_type": "document_list",
        "owner": "engineering",
        "boundary": "ECN action tasks scoped to a single ECN",
    },
    "/ecn/<id>/action-tasks/generate": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "generate action tasks (purchase change, work-order change, pick adjust, drawing replace, service notice) from an ECN's impact results",
    },
    "/ecn/action-tasks/<id>/status": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "engineering",
        "boundary": "update an ECN action task's status and assignee",
    },
    # P0-5 data-level permission control
    "/security/data-permissions": {
        "classification": "live",
        "page_type": "system_admin_query",
        "owner": "system",
        "boundary": "data permission rules list; filters by subject, scope, and permission",
    },
    "/system/opening-period": {
        "classification": "live",
        "page_type": "system_admin",
        "owner": "system",
        "boundary": "opening time and enabled period settings backed by system_options",
    },
    "/system/opening-period/save": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "save opening time and enabled period settings; does not create business documents or post finance records",
    },
    "/system/doc-rules": {
        "classification": "live",
        "page_type": "system_admin",
        "owner": "system",
        "boundary": "document number rule settings; controls future generated document numbers only",
    },
    "/system/doc-rules/save": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "save document number rules; does not rewrite historical document numbers",
    },
    "/security/data-permissions/new": {
        "classification": "live",
        "page_type": "system_admin",
        "owner": "system",
        "boundary": "data permission rule creation form/action; mirrors rule to data_scope_rules for query-scope enforcement",
    },
    "/security/data-permissions/<id>/update": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "update an existing data permission rule",
    },
    "/security/data-permissions/<id>/delete": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "delete a data permission rule; restricted to admin and manager",
    },
    "/security/data-access-logs": {
        "classification": "readonly",
        "page_type": "system_admin_query",
        "owner": "system",
        "boundary": "data access audit log query; read-only view of view/export/edit access decisions",
    },
    "/security/export-approvals": {
        "classification": "live",
        "page_type": "system_admin_query",
        "owner": "system",
        "boundary": "export approval queue; list pending and processed export approval requests with approve/reject/cancel actions",
    },
    "/security/export-approvals/new": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "create an export approval request; status starts as pending",
    },
    "/security/export-approvals/<id>/approve": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "approve a pending export approval request",
    },
    "/security/export-approvals/<id>/reject": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "reject a pending export approval request",
    },
    "/security/export-approvals/<id>/cancel": {
        "classification": "live",
        "page_type": "system_admin_action",
        "owner": "system",
        "boundary": "cancel own pending export approval request",
    },
    "/api/data-permissions/scopes": {
        "classification": "readonly",
        "page_type": "internal_api",
        "owner": "system",
        "boundary": "JSON endpoint returning available scope options for a given scope type; consumed by the rule form",
    },
    "/inventory/inbound/<doc_no>/audit": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "audit a draft other-inbound document; promotes header status to posted and applies every line to stock_transactions and inventory_balances atomically",
    },
    "/inventory/inbound/<doc_no>/unaudit": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "reverse an audited other-inbound document; reverses balance effects, removes posting stock_transactions rows, and resets header status to draft; refuses to drive balances below zero",
    },
    "/inventory/inbound/<doc_no>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an other-inbound document into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/inventory/inbound/<doc_no>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft other-inbound document after confirming it has no posting stock_transactions; posted documents must be reversed before deletion",
    },
    "/inventory/outbound/<doc_no>/audit": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "audit a draft other-outbound document; promotes header status to posted and applies every line to stock_transactions and inventory_balances atomically",
    },
    "/inventory/outbound/<doc_no>/unaudit": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "reverse an audited other-outbound document; reverses balance effects, removes posting stock_transactions rows, and resets header status to draft; refuses to drive balances below zero",
    },
    "/inventory/outbound/<doc_no>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an other-outbound document into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/inventory/outbound/<doc_no>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft other-outbound document after confirming it has no posting stock_transactions; posted documents must be reversed before deletion",
    },
    "/purchase_receipts/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase/warehouse",
        "boundary": "copy a purchase receipt into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/purchase_receipts/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase/warehouse",
        "boundary": "delete a draft purchase receipt after confirming it has no posting stock_transactions; posted receipts must be reversed before deletion",
    },
    "/shipments/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales/warehouse",
        "boundary": "copy a sales shipment into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/shipments/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales/warehouse",
        "boundary": "delete a draft sales shipment after confirming it has no posting stock_transactions; posted shipments must be reversed before deletion",
    },
    "/sales-returns/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales/warehouse",
        "boundary": "copy a sales return into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/sales-returns/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales/warehouse",
        "boundary": "delete a draft sales return after confirming it has no posting stock_transactions; posted returns must be reversed before deletion",
    },
    "/purchase-returns/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase/warehouse",
        "boundary": "copy a purchase return into a new draft document number with the same line details; does not post stock until the copied document is audited",
    },
    "/purchase-returns/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase/warehouse",
        "boundary": "delete a draft purchase return after confirming it has no posting stock_transactions; posted returns must be reversed before deletion",
    },
    "/adjustments/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an inventory adjustment into a new draft document with the same line details; does not post stock until the copied document is audited",
    },
    "/adjustments/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft inventory adjustment after confirming it has no posting stock_transactions; posted adjustments must be reversed before deletion",
    },
    "/transfers/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an inventory transfer into a new draft document with the same line details; does not post stock until the copied document is audited",
    },
    "/transfers/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft inventory transfer after confirming it has no posting stock_transactions; posted transfers must be reversed before deletion",
    },
    "/inventory_checks/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an inventory check into a new draft document with the same line details; does not post stock until the copied document is audited",
    },
    "/inventory_checks/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft inventory check after confirming it has no posting stock_transactions; posted checks must be reversed before deletion",
    },
    "/assembly-orders/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy an assembly order into a new draft document with the same line details; does not post stock until the copied document is audited",
    },
    "/assembly-orders/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft assembly order after confirming it has no posting stock_transactions; posted assembly orders must be reversed before deletion",
    },
    "/disassembly-orders/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "copy a disassembly order into a new draft document with the same line details; does not post stock until the copied document is audited",
    },
    "/disassembly-orders/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "inventory/warehouse",
        "boundary": "delete a draft disassembly order after confirming it has no posting stock_transactions; posted disassembly orders must be reversed before deletion",
    },
    "/production-completions/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/warehouse",
        "boundary": "copy a production completion receipt into a new draft document with the same header details; does not post stock until the copied document is submitted and audited",
    },
    "/production-completions/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/warehouse",
        "boundary": "delete a draft production completion receipt before any completion posting, work-order completion item, or stock transaction exists",
    },
    "/production-issues/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/warehouse",
        "boundary": "copy a production pick document into a new draft document with the same line details; does not post stock until the copied document is submitted and audited",
    },
    "/production-returns/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "production/warehouse",
        "boundary": "copy a production return document into a new draft document with the same line details; does not post stock until the copied document is submitted and audited",
    },
    "/subcontract_issue/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "subcontracting/warehouse",
        "boundary": "copy a subcontract issue into a new draft document with the same line details; does not post stock until the copied document is submitted and audited",
    },
    "/subcontract_issue/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "subcontracting/warehouse",
        "boundary": "delete a draft subcontract issue after confirming it has no posting stock_transactions; audited issues must be reversed before deletion",
    },
    "/subcontract_receive/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "subcontracting/warehouse",
        "boundary": "copy a subcontract receive into a new draft document with the same line details; does not post stock until the copied document is submitted and audited",
    },
    "/subcontract_receive/<id>/delete": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "subcontracting/warehouse",
        "boundary": "delete a draft subcontract receive after confirming it has no posting stock_transactions; audited receives must be reversed before deletion",
    },
    "/supplier-quotes/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase",
        "boundary": "copy a supplier quote into a new draft document with the same line details; does not create purchase orders until the copied document is confirmed",
    },
    "/quotations/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales",
        "boundary": "copy a sales quotation into a new draft document with the same line details",
    },
    "/sales/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "sales",
        "boundary": "copy a sales order into a new draft document with the same line details; does not affect original order quantities or shipment records",
    },
    "/purchase_order/<id>/copy": {
        "classification": "live",
        "page_type": "document_entry_action",
        "owner": "purchase",
        "boundary": "copy a purchase order into a new draft document with the same line details; does not affect original order quantities or receipt records",
    },
}
