"""Document operation blueprints defining required fields and operations per document type."""
DOCUMENT_OPERATION_BLUEPRINTS = [
    {
        "area": "销售",
        "document": "销售订单",
        "route": "/sales-orders",
        "required_fields": "客户, 日期, 交期, 项目号, 柜号, 发货仓库, 物料, 规格, 单位, 数量, 未税单价, 税率, 批号, 未税金额, 税额, 含税金额",
        "operations": "保存, 提交, 审核, 反审核, 关闭, 作废, 复制, 打印, 发货, 收款, 附件, 备注",
        "first_batch": "已具备核心字段；继续强化项目/柜号追踪、状态下一步和下游发货/收款入口",
        "risk": "发货和收款会写库存/应收，需专项验证",
    },
    {
        "area": "采购",
        "document": "采购申请",
        "route": "/purchase_request",
        "required_fields": "申请日期, 需求日期, 项目号, 柜号, 需求来源, 物料, 规格, 单位, 数量, 建议供应商, 备注",
        "operations": "保存, 转采购订单, 打印, 附件, 备注",
        "first_batch": "补齐项目/柜号、需求来源和缺料来源可见性",
        "risk": "转采购订单会生成下游单据，需专项验证",
    },
    {
        "area": "采购",
        "document": "采购订单",
        "route": "/purchase-orders",
        "required_fields": "供应商, 日期, 预计到货, 项目号, 柜号, 收货仓库, 物料, 规格, 单位, 数量, 未税单价, 税率, 批号, 未税金额, 税额, 含税金额",
        "operations": "保存, 提交, 审核, 反审核, 关闭, 作废, 复制, 打印, 收货, 付款, 附件, 备注",
        "first_batch": "已具备核心字段；继续强化到货状态、未收数量和下游收货/付款入口",
        "risk": "收货和付款会写库存/应付，需专项验证",
    },
    {
        "area": "库存",
        "document": "手工入库/出库",
        "route": "/inventory/inbound",
        "required_fields": "仓库, 库位, 日期, 来源单号, 物料, 规格, 单位, 数量, 成本, 批号, 柜号, 备注",
        "operations": "保存, 审核过账, 反审核, 增行, 插入, 复制, 粘贴, 上移, 下移, 删除, 筛选, 列设置, 自定义字段",
        "first_batch": "当前字段可支撑库存流水追溯；保存只生成草稿，审核才写库存余额和流水",
        "risk": "审核会写库存余额和流水，需专项验证",
    },
    {
        "area": "库存",
        "document": "库存调拨",
        "route": "/transfers",
        "required_fields": "调出仓库/库位, 调入仓库/库位, 日期, 物料, 规格, 单位, 数量, 成本, 批号, 柜号, 调拨原因",
        "operations": "保存, 审核过账, 反审核, 打印, 附件, 备注, 增行, 插入, 复制, 粘贴, 上移, 下移, 删除, 筛选, 列设置, 自定义字段",
        "first_batch": "当前字段可支撑仓库/库位/批号/柜号追溯；保存只生成待过账单据",
        "risk": "审核会同时写调出和调入库存流水",
    },
    {
        "area": "库存",
        "document": "库存盘点",
        "route": "/inventory_checks",
        "required_fields": "仓库, 库位, 盘点日期, 物料, 规格, 单位, 账面数量, 实盘数量, 差异数量, 成本, 批号, 柜号, 差异原因",
        "operations": "保存, 审核过账, 反审核, 打印, 附件, 备注, 增行, 粘贴, 筛选, 列设置, 自定义字段",
        "first_batch": "保存只记录盘点差异；审核后才按差异调整库存",
        "risk": "审核会按差异写库存调整流水",
    },
    {
        "area": "生产",
        "document": "生产工单",
        "route": "/work-orders",
        "required_fields": "工单号, 产品, BOM版本, 工艺路线, 计划数量, 计划日期, 项目号, 柜号, 仓库, 状态, 备注",
        "operations": "查看, 打印领料单, 打印完工单, 一键领料, 退料, 新增需求, 补料, 完工入库, 质检, 附件, 备注",
        "first_batch": "已补产品分类和制造闭环；继续强化BOM/工艺/齐套/质检下一步",
        "risk": "领料、退料、补料、完工都会写库存",
    },
    {
        "area": "委外",
        "document": "委外订单/发料/收货",
        "route": "/subcontract",
        "required_fields": "委外单号, 加工厂商, 项目号, 柜号, 来源工单, 发料仓库, 收货仓库, 物料, 数量, 成本, 税额, 交期",
        "operations": "查看, 发料, 收货, 进度跟踪, 打印, 附件, 备注",
        "first_batch": "先强化列表字段、下一步和来源工单追踪",
        "risk": "委外发料/收货会写库存和成本",
    },
    {
        "area": "质量",
        "document": "质量检验",
        "route": "/production-enhance/quality-inspections",
        "required_fields": "检验单号, 来源单据, 产品, 批号, 项目号, 柜号, 检验类型, 样本数, 合格数, 不合格数, 结论, 处置措施",
        "operations": "记录, 判定, 复检, 不合格处理, 附件, 备注",
        "first_batch": "先强化来源单据、项目/柜号和处置下一步",
        "risk": "质检判定会影响后续放行、返工和库存状态",
    },
    {
        "area": "售后",
        "document": "服务单/RMA",
        "route": "/service-orders",
        "required_fields": "服务单号, 客户, 项目号, 柜号, 设备型号, 故障分类, 原因, 处理方案, 备件, 工时, 费用, 结算状态",
        "operations": "派工, 处理, 备件出库, 生成RMA, 验收, 回访, 费用登记, 关闭, 附件, 备注",
        "first_batch": "先强化柜号全生命周期追踪和备件/费用字段可见性",
        "risk": "备件出库、费用登记、RMA关闭跨库存和财务",
    },
]
