"""Pilot role permission groups defining route access for each business module."""
PILOT_PERMISSION_GROUPS = [
    {
        "key": "sales",
        "label": "销售",
        "description": "报价、销售订单、发货、退货、发票、应收、回款、项目/机号台账",
        "paths": {
            "/sales", "/sales/new", "/sales-orders", "/shipments", "/shipments/new",
            "/quotations", "/quotations/new", "/sales-returns", "/sales-returns/new",
            "/sales-forecasts", "/sales-inquiries",
            "/sales-return-requests", "/sales-exchange-requests",
            "/sales-invoices", "/sales-invoices/new", "/sales-tax-registrations",
            "/sales-reconciliations", "/receivables",
            "/customer-receipts", "/customer-receipts/new",
            "/customer-advance-receipts", "/customer-advance-receipts/new",
            "/customer-receipt-refunds", "/customer-receipt-refunds/new",
            "/customer-advance-refunds", "/customer-advance-refunds/new",
            "/customer-other-income", "/customer-other-income/new",
            "/customer-other-income-refunds", "/customer-other-income-refunds/new",
            "/finance/receivables/pending-collections",
            "/finance/receivables/merged-collections", "/finance/receivable-bills",
            "/sales/reports/pending", "/sales/reports/customer-ranking", "/sales/reports/execution",
            "/sales/reports", "/sales/reports/summary", "/sales/reports/order-execution-summary",
            "/sales/reports/customer-open-order-analysis", "/sales/reports/project-serial-open-order-analysis",
            "/sales/reports/shipment-execution-detail", "/sales/reports/invoice-execution-detail",
            "/sales/reports/shipped-goods-detail", "/sales/reports/shipped-goods-summary",
            "/sales/reports/invoice-summary", "/sales/reports/receivable-collection-detail",
            "/sales/reports/project-serial-gross-margin", "/sales/reports/price-execution-analysis",
            "/sales/reports/delivery-delay-analysis", "/sales/reports/operation-snapshot",
            "/sales/reports/daily",
            "/sales/reports/order-execution-detail", "/sales/reports/receivable-aging",
            "/sales/reports/project-serial-order-tracking", "/sales/reports/shipped-unsettled-detail",
        },
    },
    {
        "key": "tech",
        "label": "技术/BOM",
        "description": "技术确认、BOM、工艺路线、工作中心、BOM版本、ECN影响",
        "paths": {
            "/engineering/technical-confirmations", "/engineering/technical-confirmations/new",
            "/product-configurations", "/product-configurations/new",
            "/engineering/drawings", "/engineering/drawings/new",
            "/bom", "/bom/new", "/bom/ecn", "/bom/ecn/new",
            "/bom/versions", "/bom/versions/new",
            "/ecn/impact-tasks",
            "/ecn/action-tasks",
            "/production-routings", "/work-centers",
        },
    },
    {
        "key": "purchase",
        "label": "采购/委外",
        "description": "采购申请、供应商报价、采购订单、采购入库、委外、应付",
        "paths": {
            "/purchase_request", "/purchase_request/new",
            "/purchase_order/new",
            "/purchase-orders", "/purchase_receipts", "/purchase_receipts/new",
            "/purchase-returns", "/purchase-returns/new", "/purchase-invoices",
            "/purchase-invoices/new", "/supplier-quotes", "/supplier-quotes/new",
            "/subcontract", "/subcontract/new", "/subcontract_issue", "/subcontract_issue/new",
            "/subcontract_receive", "/subcontract_receive/new", "/payables", "/payments",
            "/payments/new", "/procurement/suggestions", "/inventory/reports/subcontract-wip",
            "/inventory/reports/subcontract-execution",
            "/inventory/reports/subcontract-inout-detail",
            "/inventory/reports/subcontract-variance",
            "/inventory/reports/subcontract-payable-reconcile",
            "/purchase/reports/daily",
            "/purchase/reports/execution",
            "/purchase/reports/invoice-detail",
            "/purchase/reports/invoice-summary",
            "/purchase/reports/order-execution-detail",
            "/purchase/reports/order-execution-summary",
            "/purchase/reports/payable-reconciliation-detail",
            "/purchase/reports/payment-overview",
            "/purchase/reports/pending",
            "/purchase/reports/project-serial-purchase-cost-detail",
            "/purchase/reports/purchase-exception-list",
            "/purchase/reports/purchase-price-variance",
            "/purchase/reports/receipt-detail",
            "/purchase/reports/receipt-summary",
            "/purchase/reports/receipt-tracking",
            "/purchase/reports/received-not-invoiced-detail",
            "/purchase/reports/received-not-invoiced-summary",
            "/purchase/reports/request-execution-detail",
            "/purchase/reports/request-execution-summary",
            "/purchase/reports/summary",
            "/purchase/reports/supplier-execution-analysis",
            "/purchase/reports/supplier-ranking",
            "/subcontract/opening", "/subcontract/opening/new",
        },
    },
    {
        "key": "inventory",
        "label": "库存",
        "description": "库存、流水、调拨、盘点、批次/机号追溯",
        "paths": {
            "/inventory/detail", "/transactions", "/inventory/inbound",
            "/inventory/outbound", "/transfers", "/transfers/new", "/assembly-orders",
            "/assembly-orders/new", "/disassembly-orders", "/disassembly-orders/new",
            "/adjustments", "/adjustments/new", "/inventory_checks", "/inventory_checks/new",
            "/inventory_alerts", "/batch/tracking", "/inventory/reports",
            "/inventory/reports/shortage",
            "/inventory/reports/turnover", "/inventory/reports/batch-trace",
            "/inventory/reports/fund-occupation", "/inventory/reports/inout-summary",
            "/inventory/reports/ledger",
            "/inventory/reports/account-book",
            "/inventory/reports/available-stock",
            "/inventory/reports/balance",
            "/inventory/reports/check-difference",
            "/inventory/reports/inout-detail",
            "/inventory/reports/location-stock",
            "/inventory/reports/monthly",
            "/inventory/reports/project-occupation",
            "/inventory/opening", "/inventory/opening/new",
            "/mobile/scan",
        },
    },
    {
        "key": "production",
        "label": "生产",
        "description": "工单、齐套、MRP引擎、领料、排程、质检、生产报表",
        "paths": {
            "/work-orders", "/work-orders/new", "/engineering/kitting",
            "/production-issues", "/production-issues/new",
            "/production-returns", "/production-returns/new",
            "/production-completions", "/production-completions/new",
            "/production/operation-reports", "/production/operation-reports/new",
            "/production-enhance/mrp-requirements", "/procurement/suggestions", "/requisition",
            "/mrp", "/mrp/runs", "/mrp/suggestions", "/mrp/kitting",
            "/production-schedules", "/production-enhance/quality-inspections",
            "/production-enhance/quality-inspections/new", "/production/reports",
            "/production/reports/shortage", "/production/reports/work-order-detail",
            "/production/reports/bom-cost-query",
            "/production/reports/bom-forward-query",
            "/production/reports/bom-reverse-query",
            "/production/reports/completion-inbound-summary",
            "/production/reports/cost-accounting",
            "/production/reports/kitting-shortage",
            "/production/reports/material-issue-summary",
            "/production/reports/material-return-detail",
            "/production/reports/material-variance",
            "/production/reports/monthly-summary",
            "/production/reports/operation-report-summary",
            "/production/reports/production-cost-variance",
            "/production/reports/progress-exception",
            "/production/reports/project-serial-production-cost",
            "/production/reports/quality-exception-summary",
            "/production/reports/quality-inspection-detail",
            "/production/reports/wip-balance",
            "/production/reports/work-order-cost-detail",
            "/production/reports/work-order-execution-summary",
            "/production/reports/work-order-statistics",
            "/production/reports/work-order-execution-detail",
            "/production/reports/material-issue-detail",
            "/production/reports/completion-inbound-detail",
            "/production/reports/operation-report-detail",
            "/production/reports/project-serial-progress",
        },
    },
    {
        "key": "service",
        "label": "售后服务",
        "description": "服务档案、安装验收、服务单、RMA、服务成本",
        "paths": {
            "/service-cards", "/service-acceptance", "/service-acceptance/new",
            "/service-orders", "/service-orders/new", "/service-rmas", "/service-rmas/new",
            "/service/reports/service-detail", "/service/reports/cost", "/service/reports/rma-claim",
        },
    },
    {
        "key": "finance",
        "label": "财务/成本",
        "description": "应收、应付、收款、付款、发票登记、期间结账、财务报表、成本引擎",
        "paths": {
            "/finance", "/finance/dashboard", "/finance/receivable-payable",
            "/finance/todo-documents", "/finance/business-exceptions",
            "/finance/unbilled-sales", "/finance/unreceived-purchase-invoices",
            "/finance/invoice-matching", "/finance/reports/output-tax",
            "/finance/reports/input-tax", "/finance/reports/tax-summary",
            "/cost", "/cost/runs", "/cost/reconciliation", "/cost/variance",
            "/master/chart-of-accounts", "/voucher-words", "/currencies",
            "/settlement-methods", "/tax-rates", "/finance/account-mappings",
            "/cash-bank-accounts", "/payment-terms", "/payment-channels",
            "/voucher-templates", "/electronic-accounting-archives",
            "/vat-accounting-data",
            "/finance/bank-reconciliation", "/finance/fund-daily",
            "/finance/closing-checks", "/finance/vouchers/generate",
            "/finance/vouchers/generate-batch",
            "/finance/bank-statements", "/finance/bank-statements/import",
            "/finance/fx-rates", "/finance/fx-adjustments",
            "/finance/settings", "/finance/inventory-accounting",
            "/finance/inventory-reconciliation", "/finance/cost-management",
            "/finance/project-costs", "/finance/serial-costs", "/finance/work-order-costs",
            "/finance/reports/project-profit", "/finance/reports/serial-profit",
            "/receivables", "/payables",
            "/customer-receipts", "/customer-receipts/new",
            "/customer-advance-receipts", "/customer-advance-receipts/new",
            "/customer-receipt-refunds", "/customer-receipt-refunds/new",
            "/customer-advance-refunds", "/customer-advance-refunds/new",
            "/customer-other-income", "/customer-other-income/new",
            "/customer-other-income-refunds", "/customer-other-income-refunds/new",
            "/finance/receivables", "/finance/receipts", "/finance/receipts/new",
            "/finance/advance-receipts", "/finance/advance-receipts/new",
            "/finance/receipt-refunds", "/finance/receipt-refunds/new",
            "/finance/advance-receipt-refunds", "/finance/advance-receipt-refunds/new",
            "/finance/other-income", "/finance/other-income/new",
            "/finance/other-income-refunds", "/finance/other-income-refunds/new",
            "/finance/receivables/pending-collections",
            "/finance/receivables/merged-collections", "/finance/receivable-bills",
            "/finance/payables", "/finance/payment-requests", "/finance/payments", "/finance/payments/new",
            "/payments", "/payments/new",
            "/supplier-advance-payments", "/supplier-advance-payments/new",
            "/supplier-payment-refunds", "/supplier-payment-refunds/new",
            "/supplier-advance-refunds", "/supplier-advance-refunds/new",
            "/supplier-other-expenses", "/supplier-other-expenses/new",
            "/supplier-other-expense-refunds", "/supplier-other-expense-refunds/new",
            "/finance/advance-payments", "/finance/advance-payments/new",
            "/finance/payment-refunds", "/finance/payment-refunds/new",
            "/finance/advance-payment-refunds", "/finance/advance-payment-refunds/new",
            "/finance/other-expenses", "/finance/other-expenses/new",
            "/finance/other-expense-refunds", "/finance/other-expense-refunds/new",
            "/finance/sales-invoices", "/finance/sales-invoices/new",
            "/finance/purchase-invoices", "/finance/purchase-invoices/new",
            "/sales-invoices", "/sales-invoices/new",
            "/purchase-invoices", "/purchase-invoices/new",
            "/finance/cash-bank/accounts",
            "/finance/bank-journal", "/finance/cash-journal", "/finance/cash-bank/journal", "/finance/inventory-cost/summary",
            "/finance/inventory-cost/detail", "/finance/vouchers", "/finance/period-close",
            "/finance/period-closing/", "/finance/period-closing/check",
            "/finance/period-closing/history",
            "/finance/exchange-adjustment", "/finance/exchange-adjustments",
            "/finance/financial-statements", "/finance/reports/project-cost",
            "/finance/reports/machine-cost", "/finance/reports/aging",
            "/finance/reports/aging-buckets", "/finance/reports/balance",
            "/finance/reports/balance-sheet", "/finance/reports/income-statement",
            "/finance/reports/cash-flow-statement",
            "/finance/inventory-costing", "/finance/inventory-costing/cost-ledger",
            "/finance/inventory-costing/reconciliation",
            "/finance/project-cost/detail", "/finance/project-cost/summary",
            "/finance/project-cost/gross-profit",
            "/finance/serial-cost/detail", "/finance/serial-cost/summary",
            "/finance/serial-cost/variance",
            "/finance/reports/sales-invoice-reconciliation",
            "/finance/reports/purchase-invoice-reconciliation",
            "/finance/reports/sales-three-way-match",
            "/finance/reports/purchase-three-way-match",
            "/finance/reports/uninvoiced-sales",
            "/finance/reports/unreceived-purchase-invoice",
            "/finance/opening-balances",
            "/finance/reports/account-detail-ledger", "/finance/reports/trial-balance",
            "/finance/reports/receivable-detail", "/finance/reports/payable-detail",
            "/finance/reports/receivable-summary", "/finance/reports/payable-summary",
            "/finance/reports/payment-request-statistics",
            "/finance/reports/receivable-warning", "/finance/reports/payable-warning",
            "/finance/reports/bad-debt-reserve-balance",
            "/finance/reports/customer-statement", "/finance/reports/supplier-statement",
            "/finance/reports/customer-vendor-matching-statement",
            "/finance/reports/statement-history", "/finance/statement-templates",
            "/finance/reports/sales-collection-reconciliation",
            "/finance/reports/purchase-payment-reconciliation",
            "/finance/settlement-schemes", "/finance/settlement-runs",
            "/finance/manual-settlement", "/finance/smart-collections",
            "/finance/smart-payments",
            "/finance/reports/payment-flow-summary", "/finance/reports/project-capital-occupation",
            "/finance/reports/enterprise-income-expense-detail",
            "/finance/credit-management", "/finance/reports/credit-management",
            "/finance/reports/account-aging-analysis",
            "/finance/reports/other-income-expense-detail",
            "/finance/reports/account-income-expense-detail",
            "/finance/reports/account-balance",
            "/finance/reports/cash-bank-balance", "/finance/reports/cash-bank-transactions",
            "/finance/opening/receivables", "/finance/opening/receivables/new",
            "/finance/opening/payables", "/finance/opening/payables/new",
        },
    },
    {
        "key": "master",
        "label": "基础资料",
        "description": "物料、客户、供应商、仓库、部门、员工、分类",
        "paths": {
            "/material", "/products", "/customer", "/customers", "/supplier", "/suppliers",
            "/warehouse", "/warehouses", "/locations", "/location", "/unit", "/units",
            "/department", "/departments", "/employee", "/employees",
            "/categories/product", "/categories/customer", "/categories/supplier",
            "/categories/warehouse", "/project-master", "/machine-serial-master",
            "/export/products", "/export/customers", "/export/suppliers",
            "/export/warehouses", "/export/locations", "/export/units",
            "/export/departments", "/export/employees", "/export/project-masters",
            "/export/machine-serial-masters", "/export/product-categories",
            "/export/customer-categories", "/export/supplier-categories",
            "/export/warehouse-categories",
            "/income-categories", "/expense-categories", "/fee-templates",
            "/auxiliary-data", "/settlement-terms",
        },
    },
    {
        "key": "system",
        "label": "系统",
        "description": "用户、角色权限、操作日志、数据健康、数据权限",
        "paths": {
            "/users",
            "/permissions/roles",
            "/operation_logs",
            "/system/options",
            "/system_settings/form",
            "/system/opening-period",
            "/system/doc-rules",
            "/system/print-templates",
            "/system/database-backups",
            "/system/version-updates",
            "/system/data-health",
            "/notifications",
            "/security/locked-accounts",
            "/security/sessions",
            "/security/data-permissions",
            "/security/data-permissions/new",
            "/security/data-access-logs",
            "/security/export-approvals",
            "/security/export-approvals/new",
            "/monitoring",
            "/export/batch",
            "/management/cockpit",
            "/system/archive",
        },
    },
]

PILOT_PERMISSION_ACTIONS = [
    {"key": "view", "label": "查看"},
    {"key": "create", "label": "新增"},
    {"key": "edit", "label": "修改"},
    {"key": "audit", "label": "审核"},
    {"key": "delete", "label": "删除"},
    {"key": "operate", "label": "操作"},
    {"key": "print", "label": "打印"},
    {"key": "export", "label": "导出"},
]

PILOT_PERMISSION_FEATURES = [
    {"key": "sales_order", "group": "sales", "label": "销售订单", "path": "/sales", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "shipment", "group": "sales", "label": "销售发货", "path": "/shipments", "default_actions": {"view", "create", "operate", "delete", "print", "export"}},
    {"key": "shipment_edit", "group": "sales", "label": "修改发货单", "path": "/shipments", "default_actions": {"view", "create", "edit", "operate", "delete", "print", "export"}},
    {"key": "quotation", "group": "sales", "label": "设备报价", "path": "/quotations", "default_actions": {"view", "create", "edit", "audit", "print", "export"}},
    {"key": "sales_forecast", "group": "sales", "label": "销售预测单", "path": "/sales-forecasts", "default_actions": {"view", "create", "export"}},
    {"key": "sales_inquiry", "group": "sales", "label": "询价单", "path": "/sales-inquiries", "default_actions": {"view", "create", "export"}},
    {"key": "sales_return", "group": "sales", "label": "销售退货", "path": "/sales-returns", "default_actions": {"view", "create", "operate", "delete", "print", "export"}},
    {"key": "sales_return_edit", "group": "sales", "label": "修改退货单", "path": "/sales-returns", "default_actions": {"view", "create", "edit", "operate", "delete", "print", "export"}},
    {"key": "sales_return_request", "group": "sales", "label": "销售退货申请", "path": "/sales-return-requests", "default_actions": {"view", "create", "operate", "print", "export"}},
    {"key": "sales_exchange_request", "group": "sales", "label": "销售换货申请", "path": "/sales-exchange-requests", "default_actions": {"view", "create", "operate", "print", "export"}},
    {"key": "sales_invoice", "group": "sales", "label": "销售发票", "path": "/sales-invoices", "default_actions": {"view", "create", "operate", "print", "export"}},
    {"key": "sales_invoice_edit", "group": "sales", "label": "修改销售发票", "path": "/sales-invoices", "default_actions": {"view", "create", "edit", "operate", "print", "export"}},
    {"key": "sales_tax_registration", "group": "sales", "label": "销售税票登记", "path": "/sales-tax-registrations", "default_actions": {"view", "create", "operate", "print", "export"}},
    {"key": "sales_reconciliation", "group": "sales", "label": "销售对等核销", "path": "/sales-reconciliations", "default_actions": {"view", "export"}},
    {"key": "receivable", "group": "sales", "label": "应收账款", "path": "/receivables", "default_actions": {"view", "operate", "export"}},
    {"key": "customer_receipt", "group": "finance", "label": "收款单", "path": "/customer-receipts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_advance_receipt", "group": "finance", "label": "预收款单", "path": "/customer-advance-receipts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_receipt_refund", "group": "finance", "label": "收款退款单", "path": "/customer-receipt-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_advance_refund", "group": "finance", "label": "预收退款单", "path": "/customer-advance-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_other_income", "group": "finance", "label": "其他收入单", "path": "/customer-other-income", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_other_income_refund", "group": "finance", "label": "其他收入退款单", "path": "/customer-other-income-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "technical_confirmation", "group": "tech", "label": "技术确认单", "path": "/engineering/technical-confirmations", "default_actions": {"view", "create", "edit", "audit", "print", "export"}},
    {"key": "technical_confirmation_new", "group": "tech", "label": "新增技术确认单", "path": "/engineering/technical-confirmations/new", "default_actions": {"view", "create"}},
    {"key": "product_configuration", "group": "tech", "label": "产品选配单", "path": "/product-configurations", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "product_configuration_new", "group": "tech", "label": "新增产品选配单", "path": "/product-configurations/new", "default_actions": {"view", "create"}},
    {"key": "engineering_drawing", "group": "tech", "label": "图纸台账", "path": "/engineering/drawings", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "engineering_drawing_new", "group": "tech", "label": "新增图纸", "path": "/engineering/drawings/new", "default_actions": {"view", "create"}},
    {"key": "bom", "group": "tech", "label": "BOM清单", "path": "/bom", "default_actions": {"view", "create", "edit", "delete", "print", "export"}},
    {"key": "bom_new", "group": "tech", "label": "新增BOM", "path": "/bom/new", "default_actions": {"view", "create"}},
    {"key": "bom_ecn", "group": "tech", "label": "BOM工程变更", "path": "/bom/ecn", "default_actions": {"view", "create", "edit", "audit", "print", "export"}},
    {"key": "routing", "group": "tech", "label": "工艺路线", "path": "/production-routings", "default_actions": {"view", "create", "edit", "audit", "delete", "print", "export"}},
    {"key": "work_center", "group": "tech", "label": "工作中心", "path": "/work-centers", "default_actions": {"view", "create", "edit", "audit", "delete", "print", "export"}},
    {"key": "purchase_request", "group": "purchase", "label": "采购申请", "path": "/purchase_request", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "supplier_quote", "group": "purchase", "label": "供应商报价", "path": "/supplier-quotes", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "supplier_quote_edit", "group": "purchase", "label": "修改供应商报价", "path": "/supplier-quotes", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "purchase_order", "group": "purchase", "label": "采购订单", "path": "/purchase-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "purchase_receipt", "group": "purchase", "label": "采购入库", "path": "/purchase_receipts", "default_actions": {"view", "create", "operate", "delete", "print", "export"}},
    {"key": "purchase_receipt_edit", "group": "purchase", "label": "修改采购入库", "path": "/purchase_receipts", "default_actions": {"view", "create", "edit", "operate", "delete", "print", "export"}},
    {"key": "purchase_return", "group": "purchase", "label": "采购退货", "path": "/purchase-returns", "default_actions": {"view", "create", "operate", "delete", "print", "export"}},
    {"key": "purchase_return_edit", "group": "purchase", "label": "修改采购退货", "path": "/purchase-returns", "default_actions": {"view", "create", "edit", "operate", "delete", "print", "export"}},
    {"key": "purchase_invoice_edit", "group": "purchase", "label": "修改采购发票", "path": "/purchase-invoices", "default_actions": {"view", "create", "edit", "operate", "print", "export"}},
    {"key": "subcontract", "group": "purchase", "label": "委外订单", "path": "/subcontract", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "subcontract_issue", "group": "purchase", "label": "委外发料", "path": "/subcontract_issue", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "subcontract_receive", "group": "purchase", "label": "委外收货", "path": "/subcontract_receive", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_balance", "group": "inventory", "label": "库存明细", "path": "/inventory/detail", "default_actions": {"view", "export"}},
    {"key": "stock_transactions", "group": "inventory", "label": "库存流水", "path": "/transactions", "default_actions": {"view", "print", "export"}},
    {"key": "inventory_other_inbound", "group": "inventory", "label": "其他入库单", "path": "/inventory/inbound", "default_actions": {"view", "create", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_other_outbound", "group": "inventory", "label": "其他出库单", "path": "/inventory/outbound", "default_actions": {"view", "create", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_adjustment", "group": "inventory", "label": "库存调整", "path": "/adjustments", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_transfer", "group": "inventory", "label": "库存调拨", "path": "/transfers", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_assembly", "group": "inventory", "label": "组装单", "path": "/assembly-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_disassembly", "group": "inventory", "label": "拆卸单", "path": "/disassembly-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "inventory_check", "group": "inventory", "label": "库存盘点", "path": "/inventory_checks", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "work_order", "group": "production", "label": "生产工单", "path": "/work-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "work_order_edit", "group": "production", "label": "修改工单", "path": "/work-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "work_order_new", "group": "production", "label": "新增生产工单", "path": "/work-orders/new", "default_actions": {"view", "create"}},
    {"key": "production_issue", "group": "production", "label": "生产领料单", "path": "/production-issues", "default_actions": {"view", "create", "audit", "operate", "print", "export"}},
    {"key": "production_issue_edit", "group": "production", "label": "修改领料单", "path": "/production-issues", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "production_return", "group": "production", "label": "生产退料单", "path": "/production-returns", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "production_completion", "group": "production", "label": "完工入库单", "path": "/production-completions", "default_actions": {"view", "create", "audit", "operate", "delete", "print", "export"}},
    {"key": "production_completion_edit", "group": "production", "label": "修改完工入库", "path": "/production-completions", "default_actions": {"view", "create", "edit", "audit", "operate", "delete", "print", "export"}},
    {"key": "operation_report", "group": "production", "label": "工序报工", "path": "/production/operation-reports", "default_actions": {"view", "create", "edit", "audit", "operate", "export"}},
    {"key": "kitting", "group": "production", "label": "齐套检查", "path": "/engineering/kitting", "default_actions": {"view", "operate", "export"}},
    {"key": "mrp_shortage", "group": "production", "label": "MRP缺料", "path": "/production-enhance/mrp-requirements", "default_actions": {"view", "operate", "export"}},
    {"key": "procurement_suggestion", "group": "production", "label": "缺料转采购", "path": "/procurement/suggestions", "default_actions": {"view", "operate", "export"}},
    {"key": "requisition", "group": "production", "label": "工单领料", "path": "/requisition", "default_actions": {"view", "operate", "print", "export"}},
    {"key": "quality", "group": "production", "label": "质量检验", "path": "/production-enhance/quality-inspections", "default_actions": {"view", "create", "edit", "audit", "operate", "export"}},
    {"key": "quality_inspection_edit", "group": "production", "label": "修改质检单", "path": "/production-enhance/quality-inspections", "default_actions": {"view", "create", "edit", "audit", "operate", "export"}},
    {"key": "service_card", "group": "service", "label": "服务档案", "path": "/service-cards", "default_actions": {"view", "create", "edit", "print", "export"}},
    {"key": "service_acceptance", "group": "service", "label": "安装验收", "path": "/service-acceptance", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "service_order", "group": "service", "label": "服务单", "path": "/service-orders", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "service_rma", "group": "service", "label": "RMA", "path": "/service-rmas", "default_actions": {"view", "create", "edit", "audit", "operate", "print", "export"}},
    {"key": "project_delivery_workbench", "group": "sales", "label": "项目交付工作台", "path": "/project-delivery-workbench", "default_actions": {"view"}},
    {"key": "finance_ar_ap_workbench", "group": "finance", "label": "应收应付工作台", "path": "/finance/receivable-payable", "default_actions": {"view"}},
    {"key": "finance_receivable", "group": "finance", "label": "应收单", "path": "/finance/receivables", "default_actions": {"view", "operate", "export"}},
    {"key": "finance_receipt", "group": "finance", "label": "收款单", "path": "/finance/receipts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_advance_receipt", "group": "finance", "label": "预收款单", "path": "/finance/advance-receipts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_receipt_refund", "group": "finance", "label": "收款退款单", "path": "/finance/receipt-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_advance_receipt_refund", "group": "finance", "label": "预收退款单", "path": "/finance/advance-receipt-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_other_income", "group": "finance", "label": "其他收入单", "path": "/finance/other-income", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_other_income_refund", "group": "finance", "label": "其他收入退款单", "path": "/finance/other-income-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_receivable_pending_collection", "group": "finance", "label": "待收款清单", "path": "/finance/receivables/pending-collections", "default_actions": {"view", "export"}},
    {"key": "finance_receivable_merged_collection", "group": "finance", "label": "合并收款记录列表", "path": "/finance/receivables/merged-collections", "default_actions": {"view", "export"}},
    {"key": "finance_receivable_bill", "group": "finance", "label": "应收票据", "path": "/finance/receivable-bills", "default_actions": {"view", "export"}},
    {"key": "payable", "group": "finance", "label": "应付单", "path": "/finance/payables", "default_actions": {"view", "operate", "export"}},
    {"key": "supplier_payment", "group": "finance", "label": "付款单", "path": "/finance/payments", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_advance_payment", "group": "finance", "label": "预付款单", "path": "/finance/advance-payments", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_payment_refund", "group": "finance", "label": "付款退款单", "path": "/finance/payment-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_advance_refund", "group": "finance", "label": "预付退款单", "path": "/finance/advance-payment-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_other_expense", "group": "finance", "label": "其他支出单", "path": "/finance/other-expenses", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_other_expense_refund", "group": "finance", "label": "其他支出退款单", "path": "/finance/other-expense-refunds", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_sales_invoice", "group": "finance", "label": "销售发票", "path": "/finance/sales-invoices", "default_actions": {"view", "create", "edit", "operate", "print", "export"}},
    {"key": "finance_purchase_invoice", "group": "finance", "label": "采购发票", "path": "/finance/purchase-invoices", "default_actions": {"view", "create", "edit", "operate", "print", "export"}},
    {"key": "cash_bank_accounts", "group": "finance", "label": "现金银行账户", "path": "/finance/cash-bank/accounts", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "cash_bank_journal", "group": "finance", "label": "现金银行流水", "path": "/finance/bank-journal", "default_actions": {"view", "export"}},
    {"key": "finance_enterprise_income_expense_detail_report", "group": "finance", "label": "企业收支明细表", "path": "/finance/reports/enterprise-income-expense-detail", "default_actions": {"view", "export"}},
    {"key": "finance_credit_management_report", "group": "finance", "label": "信用管理", "path": "/finance/credit-management", "default_actions": {"view", "export"}},
    {"key": "finance_account_aging_analysis_report", "group": "finance", "label": "账龄分析表", "path": "/finance/reports/account-aging-analysis", "default_actions": {"view", "export"}},
    {"key": "finance_other_income_expense_detail_report", "group": "finance", "label": "其他收支明细表", "path": "/finance/reports/other-income-expense-detail", "default_actions": {"view", "export"}},
    {"key": "finance_account_income_expense_detail_report", "group": "finance", "label": "账户收支明细表", "path": "/finance/reports/account-income-expense-detail", "default_actions": {"view", "export"}},
    {"key": "finance_fund_account_balance_report", "group": "finance", "label": "账户余额表", "path": "/finance/reports/account-balance", "default_actions": {"view", "export"}},
    {"key": "finance_cash_bank_balance_report", "group": "finance", "label": "现金银行账户余额", "path": "/finance/reports/cash-bank-balance", "default_actions": {"view", "export"}},
    {"key": "finance_cash_bank_transactions_report", "group": "finance", "label": "现金银行流水报表", "path": "/finance/reports/cash-bank-transactions", "default_actions": {"view", "export"}},
    {"key": "finance_payment_flow_summary_report", "group": "finance", "label": "收付款流水汇总", "path": "/finance/reports/payment-flow-summary", "default_actions": {"view", "export"}},
    {"key": "finance_project_capital_occupation_report", "group": "finance", "label": "项目资金占用表", "path": "/finance/reports/project-capital-occupation", "default_actions": {"view", "export"}},
    {"key": "inventory_cost_summary", "group": "finance", "label": "库存成本总账", "path": "/finance/inventory-cost/summary", "default_actions": {"view", "export"}},
    {"key": "inventory_cost_detail", "group": "finance", "label": "库存成本明细账", "path": "/finance/inventory-cost/detail", "default_actions": {"view", "export"}},
    {"key": "finance_vouchers", "group": "finance", "label": "记账凭证", "path": "/finance/vouchers", "default_actions": {"view", "export"}},
    {"key": "general_ledger", "group": "finance", "label": "总账明细", "path": "/finance/general-ledger", "default_actions": {"view", "export"}},
    {"key": "detail_ledger", "group": "finance", "label": "明细账", "path": "/finance/detail-ledger", "default_actions": {"view", "export"}},
    {"key": "account_balance_summary", "group": "finance", "label": "科目余额表", "path": "/finance/account-balance", "default_actions": {"view", "export"}},
    {"key": "trial_balance", "group": "finance", "label": "试算平衡表", "path": "/finance/trial-balance", "default_actions": {"view", "export"}},
    {"key": "period_close", "group": "finance", "label": "期间结账", "path": "/finance/period-close", "default_actions": {"view", "audit", "operate", "print", "export"}},
    {"key": "finance_exchange_adjustment", "group": "finance", "label": "期末调汇", "path": "/finance/exchange-adjustment", "default_actions": {"view", "operate", "audit", "print", "export"}},
    {"key": "finance_exchange_adjustment_list", "group": "finance", "label": "调汇单查询", "path": "/finance/exchange-adjustments", "default_actions": {"view", "export"}},
    {"key": "financial_statements", "group": "finance", "label": "经营财务快照", "path": "/finance/financial-statements", "default_actions": {"view", "export"}},
    {"key": "project_cost_report", "group": "finance", "label": "项目成本明细", "path": "/finance/reports/project-cost", "default_actions": {"view", "export"}},
    {"key": "machine_cost_report", "group": "finance", "label": "机号成本明细", "path": "/finance/reports/machine-cost", "default_actions": {"view", "export"}},
    {"key": "aging_report", "group": "finance", "label": "应收应付账龄", "path": "/finance/reports/aging", "default_actions": {"view", "export"}},
    {"key": "aging_buckets_report", "group": "finance", "label": "账龄区间汇总", "path": "/finance/reports/aging-buckets", "default_actions": {"view", "export"}},
    {"key": "partner_balance_report", "group": "finance", "label": "往来余额明细", "path": "/finance/reports/balance", "default_actions": {"view", "export"}},
    {"key": "finance_receivable_detail_report", "group": "finance", "label": "应收账款明细表", "path": "/finance/reports/receivable-detail", "default_actions": {"view", "export"}},
    {"key": "finance_payable_detail_report", "group": "finance", "label": "应付账款明细表", "path": "/finance/reports/payable-detail", "default_actions": {"view", "export"}},
    {"key": "finance_receivable_summary_report", "group": "finance", "label": "应收账款汇总表", "path": "/finance/reports/receivable-summary", "default_actions": {"view", "export"}},
    {"key": "finance_payable_summary_report", "group": "finance", "label": "应付账款汇总表", "path": "/finance/reports/payable-summary", "default_actions": {"view", "export"}},
    {"key": "finance_payment_request_statistics_report", "group": "finance", "label": "付款申请统计表", "path": "/finance/reports/payment-request-statistics", "default_actions": {"view", "export"}},
    {"key": "finance_receivable_warning_report", "group": "finance", "label": "应收账款预警表", "path": "/finance/reports/receivable-warning", "default_actions": {"view", "export"}},
    {"key": "finance_payable_warning_report", "group": "finance", "label": "应付账款预警表", "path": "/finance/reports/payable-warning", "default_actions": {"view", "export"}},
    {"key": "finance_bad_debt_reserve_balance_report", "group": "finance", "label": "坏账准备余额表", "path": "/finance/reports/bad-debt-reserve-balance", "default_actions": {"view", "export"}},
    {"key": "finance_settlement_schemes", "group": "finance", "label": "自动核销方案列表", "path": "/finance/settlement-schemes", "default_actions": {"view", "export"}},
    {"key": "finance_settlement_runs", "group": "finance", "label": "自动核销执行日志", "path": "/finance/settlement-runs", "default_actions": {"view", "export"}},
    {"key": "finance_manual_settlement", "group": "finance", "label": "手动核销", "path": "/finance/manual-settlement", "default_actions": {"view", "operate"}},
    {"key": "finance_smart_collections", "group": "finance", "label": "智能收款", "path": "/finance/smart-collections", "default_actions": {"view", "operate"}},
    {"key": "finance_smart_payments", "group": "finance", "label": "智能付款", "path": "/finance/smart-payments", "default_actions": {"view", "operate"}},
    {"key": "finance_customer_vendor_matching_statement", "group": "finance", "label": "客商匹配对账单", "path": "/finance/reports/customer-vendor-matching-statement", "default_actions": {"view", "export"}},
    {"key": "finance_statement_history", "group": "finance", "label": "历史对账单", "path": "/finance/reports/statement-history", "default_actions": {"view", "export"}},
    {"key": "finance_statement_templates", "group": "finance", "label": "对账函模板列表", "path": "/finance/statement-templates", "default_actions": {"view", "export"}},
    {"key": "material", "group": "master", "label": "物料档案", "path": "/material", "default_actions": {"view", "create", "edit", "audit", "delete", "print", "export"}},
    {"key": "customer", "group": "master", "label": "客户档案", "path": "/customer", "default_actions": {"view", "create", "edit", "delete", "print", "export"}},
    {"key": "supplier", "group": "master", "label": "供应商档案", "path": "/supplier", "default_actions": {"view", "create", "edit", "delete", "print", "export"}},
    {"key": "warehouse_master", "group": "master", "label": "仓库档案", "path": "/warehouse", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "location_master", "group": "master", "label": "库位档案", "path": "/locations", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "unit_master", "group": "master", "label": "计量单位", "path": "/unit", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "department_master", "group": "master", "label": "部门档案", "path": "/department", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "employee_master", "group": "master", "label": "员工档案", "path": "/employee", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "project_master", "group": "master", "label": "项目档案", "path": "/project-master", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "machine_serial_master", "group": "master", "label": "机号档案", "path": "/machine-serial-master", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "product_category_master", "group": "master", "label": "物料分类", "path": "/categories/product", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "customer_category_master", "group": "master", "label": "客户分类", "path": "/categories/customer", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "supplier_category_master", "group": "master", "label": "供应商分类", "path": "/categories/supplier", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "warehouse_category_master", "group": "master", "label": "仓库分类", "path": "/categories/warehouse", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "income_category", "group": "master", "label": "收入类别", "path": "/income-categories", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "expense_category", "group": "master", "label": "支出类别", "path": "/expense-categories", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "fee_template", "group": "master", "label": "费用模板", "path": "/fee-templates", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "auxiliary_data", "group": "master", "label": "辅助资料", "path": "/auxiliary-data", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "settlement_term", "group": "master", "label": "结算期限", "path": "/settlement-terms", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "payment_term", "group": "finance", "label": "收付款条件", "path": "/payment-terms", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "tax_rate", "group": "finance", "label": "税率", "path": "/tax-rates", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "finance_account_mapping", "group": "finance", "label": "科目映射", "path": "/finance/account-mappings", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "currency", "group": "finance", "label": "币别", "path": "/currencies", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "settlement_method", "group": "finance", "label": "结算方式", "path": "/settlement-methods", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "cash_bank_account_master", "group": "finance", "label": "账户管理", "path": "/cash-bank-accounts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "payment_channel", "group": "finance", "label": "支付渠道", "path": "/payment-channels", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "chart_of_account_master", "group": "finance", "label": "科目", "path": "/master/chart-of-accounts", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "voucher_word", "group": "finance", "label": "凭证字", "path": "/voucher-words", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "voucher_template", "group": "finance", "label": "凭证模板", "path": "/voucher-templates", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "electronic_accounting_archive", "group": "finance", "label": "电子会计档案", "path": "/electronic-accounting-archives", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "vat_accounting_data", "group": "finance", "label": "增值会计数据", "path": "/vat-accounting-data", "default_actions": {"view", "create", "edit", "delete", "export"}},
    {"key": "material_opening", "group": "inventory", "label": "物料期初", "path": "/inventory/opening", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "subcontract_opening", "group": "purchase", "label": "委外期初", "path": "/subcontract/opening", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "receivable_opening", "group": "finance", "label": "应收期初", "path": "/finance/opening/receivables", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "payable_opening", "group": "finance", "label": "应付期初", "path": "/finance/opening/payables", "default_actions": {"view", "create", "edit", "export"}},
    {"key": "users", "group": "system", "label": "用户管理", "path": "/users", "default_actions": {"view", "create", "edit", "delete", "operate"}},
    {"key": "role_permissions", "group": "system", "label": "角色权限", "path": "/permissions/roles", "default_actions": {"view", "edit", "operate"}},
    {"key": "operation_logs", "group": "system", "label": "操作日志", "path": "/operation_logs", "default_actions": {"view", "delete", "export"}},
    {"key": "system_settings", "group": "system", "label": "系统参数", "path": "/system_settings/form", "default_actions": {"view", "edit", "operate"}},
    {"key": "document_number_rules", "group": "system", "label": "单据编号设置", "path": "/system/doc-rules", "default_actions": {"view", "edit", "operate"}},
    {"key": "print_templates", "group": "system", "label": "打印模板", "path": "/system/print-templates", "default_actions": {"view", "create", "edit", "delete", "operate", "print"}},
    {"key": "database_backups", "group": "system", "label": "数据库备份", "path": "/system/database-backups", "default_actions": {"view", "operate", "export"}},
    {"key": "data_health", "group": "system", "label": "数据健康", "path": "/system/data-health", "default_actions": {"view", "export"}},
    {"key": "opening_period_settings", "group": "system", "label": "开账时间/启用期间", "path": "/system/opening-period", "default_actions": {"view", "edit", "operate"}},
]

PILOT_COMMON_PATHS = {
    "/",
    "/project-delivery-workbench",
    "/projects",
    "/pending-documents",
    "/approval/pending",
    "/reports",
    "/help/assistant",
    "/help/operation-manual",
    "/trace", "/trace/integrity",
    "/trace/snapshots",
}

PILOT_ROLE_LABELS = {
    "admin": "系统管理员",
    "manager": "系统主管",
    "sales": "销售",
    "purchase": "采购/委外",
    "warehouse": "仓库",
    "production": "生产",
    "service": "售后服务",
    "finance": "财务/成本",
}

PILOT_ROLE_TRIAL_USERS = {
    "admin": "pilot_admin",
    "manager": "pilot_admin",
    "sales": "pilot_sales",
    "purchase": "pilot_purchase",
    "warehouse": "pilot_warehouse",
    "production": "pilot_production",
    "service": "pilot_service",
    "finance": "pilot_finance",
}

PILOT_DEFAULT_ROLE_GROUPS = {
    "admin": {"sales", "tech", "purchase", "inventory", "production", "service", "finance", "master", "system"},
    "manager": {"sales", "tech", "purchase", "inventory", "production", "service", "finance", "master", "system"},
    "sales": {"sales", "service", "master"},
    "purchase": {"tech", "purchase", "inventory", "master"},
    "warehouse": {"inventory", "master"},
    "production": {"tech", "inventory", "production", "master"},
    "service": {"service", "master"},
    "finance": {"finance"},
}

# 角色-组级别动作覆盖：限制该角色在该组内可用的动作子集（与 default_actions 取交集）
PILOT_ROLE_ACTION_OVERRIDES = {
    ("finance", "sales"): {"view", "export", "print"},
    ("finance", "purchase"): {"view", "export", "print"},
    ("finance", "inventory"): {"view", "export"},
    ("sales", "master"): {"view"},
    ("purchase", "master"): {"view"},
    ("warehouse", "master"): {"view"},
    ("production", "master"): {"view"},
    ("service", "master"): {"view"},
    ("finance", "master"): {"view"},
}


def pilot_group_keys():
    return [group["key"] for group in PILOT_PERMISSION_GROUPS]


def pilot_paths_for_groups(group_keys):
    paths = set(PILOT_COMMON_PATHS)
    group_set = set(group_keys or ())
    for group in PILOT_PERMISSION_GROUPS:
        if group["key"] in group_set:
            paths |= set(group["paths"])
    return paths


def default_groups_for_role(role):
    return set(PILOT_DEFAULT_ROLE_GROUPS.get(role, set()))


def default_actions_for_role(role):
    if role in ("admin", "manager"):
        all_actions = sorted(action["key"] for action in PILOT_PERMISSION_ACTIONS)
        return {
            feature["key"]: all_actions
            for feature in PILOT_PERMISSION_FEATURES
        }
    group_keys = default_groups_for_role(role)
    result = {}
    for feature in PILOT_PERMISSION_FEATURES:
        if feature["group"] not in group_keys:
            continue
        actions = set(feature["default_actions"])
        group_override = PILOT_ROLE_ACTION_OVERRIDES.get((role, feature["group"]))
        if group_override is not None:
            actions = actions & group_override
        result[feature["key"]] = sorted(actions)
    return result
